### ISSUE TITLE
bbfs fails to mount ("missing field `term`"?)

### ISSUE THREAD

**Issue by katrinafyi** [BlackboardFS/bbfs#4]
Hello! It seems that mounting doesn't work. Depending on the arugments, it either does nothing or shows a "missing field" error.

```bash
$ ~/.cargo/bin/bbfs /mnt
$ ~/.cargo/bin/bbfs /mnt --all
$ ~/.cargo/bin/bbfs /mnt --monitor
FailedToParseMemberships(Error("missing field `term`", line: 1, column: 4158))
Error: failed to initialize Blackboard fs driver
$ command ls -l /mnt
total 0
$ rustc --version
rustc 1.73.0 (cc66ad468 2023-10-03) (Arch Linux rust 1:1.73.0-1)
```
Do you know what the problem might be?

When authenticating with the webview, it also shows some warnings. I'm not sure these are related.
```
WARNING: Getting tokens from fapi backend failed.
...
ERROR: Could not initialize tpm ctx: 0x5
```

**Comment by stackotter** [comment]
Ah, looks like we assumed something about the Blackboard “API” that appears to be wrong, thanks for reporting this! The errors and warnings during authentication look like they’re just from the web view library not bbfs so they can probably be ignored.

I’ll have a closer look when I get home

**Comment by stackotter** [comment]
I've updated the term field to be optional in the latest commit (1a356b20b747a873a77bd770e4c66cf58bbedbc0), let me know if that fixes your issue 🤞

**Comment by katrinafyi** [comment]
It works! Magical, thank you!

`

**Comment by stackotter** [comment]
Awesome!
